namespace MRK {
	public enum EGRLanguageData {
		//ERROR
		ERROR = 0,

		//PASSWORDS MISMATCH
		PASSWORDS_MISMATCH = 1,

		//REGISTER
		REGISTER = 2,

		//FAILED (EGR-{0})
		FAILED__EGR__0__ = 3,

		//FAILED (EGR-{0}-{1})
		FAILED__EGR__0___1__ = 4,

		//REGISTERING...
		REGISTERING___ = 5,

		//SUCCESS
		SUCCESS = 6,

		//LOGGING IN...
		LOGGING_IN___ = 7,

		//LOGIN
		LOGIN = 8,

		//WELCOME {0}
		WELCOME__0_ = 9,

		//INVALID NAME
		INVALID_NAME = 10,

		//SAVING...
		SAVING___ = 11,

		//ACCOUNT INFO
		ACCOUNT_INFO = 12,

		//SAVED
		SAVED = 13,

		//YOU HAVE UNSAVED CHANGES$nWOULD YOU LIKE TO SAVE YOUR CHANGES?
		YOU_HAVE_UNSAVED_CHANGES_nWOULD_YOU_LIKE_TO_SAVE_YOUR_CHANGES_ = 14,

		//YES
		YES = 15,

		//NO
		NO = 16,

		//SAVE
		SAVE = 17,

		//CANCEL
		CANCEL = 18,

		//LOGOUT
		LOGOUT = 19,

		//ARE YOU SURE THAT YOU WANT TO LOGOUT OF EGR?
		ARE_YOU_SURE_THAT_YOU_WANT_TO_LOGOUT_OF_EGR_ = 20,

		//LOGGING IN OFFLINE...
		LOGGING_IN_OFFLINE___ = 21,

		//GRAPHIC SETTINGS WERE MODIFIED$nWOULD YOU LIKE TO APPLY THEM?
		GRAPHIC_SETTINGS_WERE_MODIFIED_nWOULD_YOU_LIKE_TO_APPLY_THEM_ = 22,

		//APPLY
		APPLY = 23,

		//SETTINGS
		SETTINGS = 24,

		//EMAILS DO NOT MATCH
		EMAILS_DO_NOT_MATCH = 25,

		//INVALID EMAIL
		INVALID_EMAIL = 26,

		//ACCOUNTS LINKED WITH A DEVICE ID CAN NOT HAVE THEIR EMAILS CHANGED
		ACCOUNTS_LINKED_WITH_A_DEVICE_ID_CAN_NOT_HAVE_THEIR_EMAILS_CHANGED = 27,

		//INCORRECT PASSWORD
		INCORRECT_PASSWORD = 28,

		//INVALID PASSWORD
		INVALID_PASSWORD = 29,

		//ACCOUNTS LINKED WITH A DEVICE ID CAN NOT HAVE THEIR PASSWORDS CHANGED
		ACCOUNTS_LINKED_WITH_A_DEVICE_ID_CAN_NOT_HAVE_THEIR_PASSWORDS_CHANGED = 30,

		//OK
		OK = 31,

		//NAVIGATION
		NAVIGATION = 32,

		//FINDING AVAILABLE ROUTES
		FINDING_AVAILABLE_ROUTES = 33,

		//LOCATION PERMISSION MUST BE ENABLED TO BE ABLE TO USE CURRENT LOCATION
		LOCATION_PERMISSION_MUST_BE_ENABLED_TO_BE_ABLE_TO_USE_CURRENT_LOCATION = 34,

		//EGR
		EGR = 35,

		//ENABLE
		ENABLE = 36,

		//LOCATION MUST BE ENABLED TO BE ABLE TO USE CURRENT LOCATION
		LOCATION_MUST_BE_ENABLED_TO_BE_ABLE_TO_USE_CURRENT_LOCATION = 37,

		//RETRIEVING CURRENT LOCATION...
		RETRIEVING_CURRENT_LOCATION___ = 38,

		//CANNOT OBTAIN CURRENT LOCATION
		CANNOT_OBTAIN_CURRENT_LOCATION = 39,

		//START
		START = 40,

		//PREVIEW
		PREVIEW = 41,

		//LOADING CUISINES...
		LOADING_CUISINES___ = 42,

		//SEARCHING FOR <color=orange><b><size=80>{0}</size></b></color> RESTAUARANTS$n$nFOR <color=orange><b><size=80>{1}</size></b></color> PEOPLE$n$nWITH A BUDGET OF <color=orange><b><size=80>{2}EGP</size></b></color>
		SEARCHING_FOR__color_orange__b__size_80__0___size___b___color__RESTAUARANTS_n_nFOR__color_orange__b__size_80__1___size___b___color__PEOPLE_n_nWITH_A_BUDGET_OF__color_orange__b__size_80__2_EGP__size___b___color_ = 43,

		//SEARCHING...
		SEARCHING___ = 44,

		//WTE
		WTE = 45,

		//NO RESTAURANTS WERE FOUND MATCHING THE SPECIFIED CRITERIA
		NO_RESTAURANTS_WERE_FOUND_MATCHING_THE_SPECIFIED_CRITERIA = 46,

		//<b>{0}</b> RESULTS
		_b__0___b__RESULTS = 47,

		//ADD
		ADD = 48,

		//QUICK LOCATIONS
		QUICK_LOCATIONS = 49,

		//ADD CURRENT LOCATION? ({0})
		ADD_CURRENT_LOCATION____0__ = 50,

		//ENTER LOCATION NAME
		ENTER_LOCATION_NAME = 51,

		//ARE YOU SURE THAT YOU WANT TO DELETE THE OFFLINE MAP CACHE?
		ARE_YOU_SURE_THAT_YOU_WANT_TO_DELETE_THE_OFFLINE_MAP_CACHE_ = 52,

		//DELETING OFFLINE MAP CACHE...
		DELETING_OFFLINE_MAP_CACHE___ = 53,

		//OFFLINE MAP CACHE HAS BEEN DELETED
		OFFLINE_MAP_CACHE_HAS_BEEN_DELETED = 54,

		//ENTER YOUR PASSWORD AGAIN
		ENTER_YOUR_PASSWORD_AGAIN = 55,

		//DELETE
		DELETE = 56,

		//EXIT
		EXIT = 57,

		//YOU ARE EXITING <b>EGR</b>...
		YOU_ARE_EXITING__b_EGR__b____ = 58,

		//FETCHING PLACE DATA...
		FETCHING_PLACE_DATA___ = 59,

		//Email cannot be empty
		Email_cannot_be_empty = 100,

		//Email is invalid
		Email_is_invalid = 101,

		//Password cannot be empty
		Password_cannot_be_empty = 102,

		//Password must consist of atleast 8 characters
		Password_must_consist_of_atleast_8_characters = 103,

		//SETTINGS_1
		SETTINGS_1 = 1000,

		//CURRENT LOCATION
		CURRENT_LOCATION = 1001,

		//TRENDING
		TRENDING = 1002,

		//NAVIGATION_1
		NAVIGATION_1 = 1003,

		//BACK TO EARTH
		BACK_TO_EARTH = 1004,

		//FIELD OF VIEW
		FIELD_OF_VIEW = 1005,

		//SELECTION
		SELECTION = 1006,

		//{0} DAYS AGO
		_0__DAYS_AGO = 2000,

		//{0} HOURS AGO
		_0__HOURS_AGO = 2001,

		//{0} MINUTES AGO
		_0__MINUTES_AGO = 2002,

		//N/A
		N_A = 2003,

		//{0} M AWAY
		_0__M_AWAY = 2004,

		//{0} KM AWAY
		_0__KM_AWAY = 2005,

		//ARE YOU SURE THAT YOU WANT TO DELETE {0}?
		ARE_YOU_SURE_THAT_YOU_WANT_TO_DELETE__0__ = 2006,

		__LANG_DATA_MAX
	}
}
